export const GET_PUBLICATIONS = 'GET_PUBLICATIONS';
export const GET_STUDENT_PUBLICATIONS = 'GET_STUDENT_PUBLICATIONS';
export const SWAP_CALENDAR_STATE = 'SWAP_CALENDAR_STATE';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const POST_SUBMISSION = 'POST_SUBMISSION';
